services:
  - docker
  
before_install:
  - docker build -t docker-react -f Dockerfile.dev .
  
script:
  docker run --name docker-react-test docker-react npm run test -- --watchAll=false

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag docker-react $DOCKER_USERNAME/docker-react
  - docker push $DOCKER_USERNAME/docker-react