sudo: required

services:
  - docker
  
before_install:
  docker build -t vigneshdusa/docker-react -f Dockerfile.dev .
  
script:
  docker run --name docker-react-test vigneshdusa/docker-react npm run test -- --coverage
