sudo: required
services:
  - docker
before_install:
  docker build -t vigneshdusa/docker-react .
script:
  docker run --name vigneshdusa/docker-react-test vigneshdusa/docker-react npm run test -- --coverage
