name: Docker test
on:
  push:
    branches: [main, master]

jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup docker build
        uses: docker/setup-buildx-action@v3
      - name: Docker build
        run: docker build -t docker-react -f Dockerfile.test .
      - name: Run Container
        run: docker run --rm docker-react