name: Docker test
on:
  push:
    branches: [main, master]

jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup docker build
        uses: docker/setup-buildx-action@v3
      - name: Docker build
        run: docker build -t docker-react -f Dockerfile.test .
      - name: Run Container
        run: docker run --rm docker-react
  deploy:
    needs: prod
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          region: "eu-north-1"
          application_name: "docker-react"
          environment_name: "docker-react-env"
          bucket_name: "elasticbeanstalk-eu-north-1-439537465395"
          bucket_path: "docker-react"
          version_label: ${{ github.sha }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}