name: docker react test

on:
  push:
    branches: ['main', 'master']

jobs:
  react-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.test -t react-test .

      - name: Run tests inside Docker container
        run: |
          docker run --rm react-test
